import type { TranslationKey } from "./core";
export const displayKeys: Record<string, TranslationKey> = {
  "GOOD": "status.good",
  "Ready": "status.ready",
  "Recovering": "status.recovering",
  "Moderate": "status.moderate",
  "Chest": "body.Chest",
  "Back": "body.Back",
  "Shoulders": "body.Shoulders",
  "Arms": "body.Arms",
  "Core": "body.Core",
  "Legs": "body.Legs",
  "CHST": "card.chest",
  "BACK": "card.back",
  "SHLD": "card.shoulders",
  "ARMS": "card.arms",
  "CORE": "card.core",
  "LEGS": "card.legs",
  "OVERALL": "card.overall",
  "ATHLETE ID // 001": "card.athlete",
  "{finish} FINISH": "card.finish",
  "Bronze": "card.bronze",
  "Silver": "card.silver",
  "Gold": "card.gold",
  "Purple": "card.purple",
  "STANDARD": "card.standard",
  "HIGH": "card.high",
  "SHOP / MAKE IT YOURS": "shop.kicker",
  "YOUR OWN SIGNATURE": "shop.title",
  "Customization is coming soon. Coins cannot be spent yet.": "shop.note",
  "COSMETICS": "shop.cosmetics",
  "Your style is yours. Your ratings are earned.": "shop.footer",
  "Card Background": "shop.background",
  "Border": "shop.border",
  "Aura": "shop.aura",
  "Title": "shop.titleItem",
  "Badge": "shop.badge",
  "Rival Color": "shop.rivalColor",
  "Victory Effect": "shop.victory",
  "Bodyweight": "equipment.bodyweight",
  "Pull-up Bar": "equipment.pullup",
  "Low Bar": "equipment.lowBar",
  "Dumbbell": "equipment.dumbbell",
  "Barbell": "equipment.barbell",
  "Bench": "equipment.bench",
  "Cable": "equipment.cable",
  "Machine": "equipment.machine",
  "Resistance Band": "equipment.band",
  "Other": "equipment.other",
  "Strength": "category.strength",
  "Power": "category.power",
  "Endurance": "category.endurance",
  "Athletic": "category.athletic",
  "Weight + Reps": "tracking.weightReps",
  "Time": "tracking.time",
  "Beginner": "experience.beginner",
  "Intermediate": "experience.intermediate",
  "Advanced": "experience.advanced",
  "Build strength": "goal.strength",
  "Build muscle": "goal.muscle",
  "General fitness": "goal.fitness",
  "Home": "location.home",
  "Gym": "location.gym",
  "Both": "location.both",
  "Japan": "country.japan",
  "England": "country.england",
  "Germany": "country.germany",
  "Spain": "country.spain",
  "Italy": "country.italy",
  "France": "country.france",
  "Something went wrong. Please check your entries or retry. Saved training data has not been reset.": "error.generic",
  "Could not save. Please retry.": "error.save",
  "Could not save your selection. Please retry.": "error.selection",
  "Could not save workout. Please retry.": "error.workout",
  "Could not prepare workout. Please retry.": "error.prepare",
  "Could not save profile. Please retry.": "error.profile",
  "Enter height from 50–300 cm and weight from 10–500 kg, or leave them blank.": "error.measurements",
  "Enter a nonnegative starting load within the workout editor's range.": "error.load"
};
