import type { TranslationKey } from "./core";
export const displayKeys: Record<string, TranslationKey> = {
  GOOD: "status.good",
  Ready: "status.ready",
  Recovering: "status.recovering",
  Moderate: "status.moderate",
  Chest: "body.Chest",
  Back: "body.Back",
  Shoulders: "body.Shoulders",
  Arms: "body.Arms",
  Core: "body.Core",
  Legs: "body.Legs",
  CHST: "card.chest",
  BACK: "card.back",
  SHLD: "card.shoulders",
  ARMS: "card.arms",
  CORE: "card.core",
  LEGS: "card.legs",
  OVERALL: "card.overall",
  "ATHLETE ID // 001": "card.athlete",
  "{finish} FINISH": "card.finish",
  Bronze: "card.bronze",
  Silver: "card.silver",
  Gold: "card.gold",
  Purple: "card.purple",
  STANDARD: "card.standard",
  HIGH: "card.high",
  "SHOP / MAKE IT YOURS": "shop.kicker",
  "YOUR OWN SIGNATURE": "shop.title",
  "Customization is coming soon. Coins cannot be spent yet.": "shop.note",
  COSMETICS: "shop.cosmetics",
  "Your style is yours. Your ratings are earned.": "shop.footer",
  "Card Background": "shop.background",
  Border: "shop.border",
  Aura: "shop.aura",
  Title: "shop.titleItem",
  Badge: "shop.badge",
  "Rival Color": "shop.rivalColor",
  "Victory Effect": "shop.victory",
  Bodyweight: "equipment.bodyweight",
  "Pull-up Bar": "equipment.pullup",
  "Low Bar": "equipment.lowBar",
  Dumbbell: "equipment.dumbbell",
  Barbell: "equipment.barbell",
  Bench: "equipment.bench",
  Cable: "equipment.cable",
  Machine: "equipment.machine",
  "Resistance Band": "equipment.band",
  Other: "equipment.other",
  Strength: "category.strength",
  Power: "category.power",
  Endurance: "category.endurance",
  Athletic: "category.athletic",
  "Weight + Reps": "tracking.weightReps",
  Time: "tracking.time",
  Beginner: "experience.beginner",
  Intermediate: "experience.intermediate",
  Advanced: "experience.advanced",
  "Build strength": "goal.strength",
  "Build muscle": "goal.muscle",
  "General fitness": "goal.fitness",
  Home: "location.home",
  Gym: "location.gym",
  Both: "location.both",
  Japan: "country.japan",
  England: "country.england",
  Germany: "country.germany",
  Spain: "country.spain",
  Italy: "country.italy",
  France: "country.france",
  "Something went wrong. Please check your entries or retry. Saved training data has not been reset.":
    "error.generic",
  "Could not save. Please retry.": "error.save",
  "Could not save your selection. Please retry.": "error.selection",
  "Could not save workout. Please retry.": "error.workout",
  "Could not prepare workout. Please retry.": "error.prepare",
  "Could not save profile. Please retry.": "error.profile",
  "Enter height from 50–300 cm and weight from 10–500 kg, or leave them blank.":
    "error.measurements",
  "Enter a nonnegative starting load within the workout editor's range.":
    "error.load",
  ASSESSED: "player.assessed",
  PROVISIONAL: "player.provisional",
  "TRAIN / FIND YOUR FOCUS": "train.kicker",
  "PUT IN THE WORK": "train.title",
  "AI COACH": "train.coach",
  "LIVE WORKOUT": "train.live",
  "WORKOUT HISTORY": "train.history",
  "WORKOUT COMPLETE": "train.complete",
  "CUSTOM WORKOUT": "train.custom",
  "SAVED WORKOUTS": "train.saved",
  "MY EXERCISES": "train.myExercises",
  "YOUR WORKOUT": "train.yourWorkout",
  "WORKOUT SESSIONS": "train.sessions",
  "LOADING SESSIONS": "train.loadingSessions",
  "RETRY SESSIONS": "train.retrySessions",
  "RETRY WORKOUT HISTORY": "train.retryHistory",
  "RESET SESSION DATA": "train.resetSessions",
  "RESET SESSION DATA?": "train.resetSessionsQuestion",
  "Clear active and completed sessions only. A raw backup will be kept on this device first. Saved workouts and exercises are unchanged.":
    "train.resetSessionsNote",
  "Your completed workouts will appear here.": "train.historyEmpty",
  "YOUR SESSIONS": "train.yourSessions",
  "RESUME WORKOUT": "train.resume",
  "TRAINING DATA": "train.data",
  "RESET TRAINING DATA": "train.resetData",
  "RESET TRAINING DATA?": "train.resetDataQuestion",
  "Start with an empty training library. A copy of the existing saved data will be kept on this device before resetting.":
    "train.resetDataNote",
  "WORKOUT IN PROGRESS": "train.inProgress",
  "Choose your way to train.": "train.choose",
  "A short workout from your preferences and training.": "train.coachNote",
  "OPEN AI COACH": "train.openCoach",
  "Your session. Your approach.": "train.customNote",
  "CREATE WORKOUT": "train.create",
  "YOUR TRAINING": "train.yourTraining",
  "+ CREATE WORKOUT": "train.createPlus",
  "YOUR NEXT SESSION STARTS HERE": "train.emptyTitle",
  "Save a workout and make it yours.": "train.emptyNote",
  "Workout saved on this device.": "train.savedNotice",
  "Rest target ·": "train.restTarget",
  "EDIT WORKOUT": "train.edit",
  "DUPLICATE WORKOUT": "train.duplicate",
  "Workout duplicated.": "train.duplicated",
  "DELETE WORKOUT": "train.delete",
  "DELETE WORKOUT?": "train.deleteQuestion",
  "Workout deleted.": "train.deleted",
  "START WORKOUT": "train.start",
  "+ CREATE CUSTOM EXERCISE": "train.createExercisePlus",
  "Add your own movements once, then select them whenever you train.":
    "train.exerciseNote",
  "DELETE EXERCISE?": "train.deleteExerciseQuestion",
  "Exercise deleted.": "train.exerciseDeleted",
  "CREATE EXERCISE": "train.createExercise",
  "EDIT EXERCISE": "train.editExercise",
  "Exercise saved on this device.": "train.exerciseSaved",
  "DISCARD CHANGES?": "train.discardQuestion",
  "Your unsaved workout changes will be lost.": "train.discardNote",
  "WORKOUT NAME": "train.workoutName",
  "e.g. Push day": "train.workoutPlaceholder",
  "Set your targets. Adjust each set whenever you need.": "train.targetsNote",
  "BUILD YOUR SESSION": "train.build",
  "Choose your first exercise to get started.": "train.firstExercise",
  "TARGET FOR ALL SETS": "train.allTargets",
  "Targets vary by set. Changing these controls applies the shown target to every set.":
    "train.varyTargets",
  "HIDE DETAILS": "train.hideDetails",
  "EDIT SETS, REST & ORDER": "train.editDetails",
  "INDIVIDUAL SET TARGETS": "train.individualTargets",
  SET: "train.set",
  "MOVE UP": "train.moveUp",
  "MOVE DOWN": "train.moveDown",
  REMOVE: "train.remove",
  "+ ADD EXERCISE": "train.addExercisePlus",
  "SAVE WORKOUT": "train.save",
  "Save your workout to start training.": "train.saveToStart",
  REST: "train.rest",
  "Rest remaining": "train.restRemaining",
  "SKIP REST": "train.skipRest",
  TARGET: "train.target",
  "Target ·": "train.targetLabel",
  "Actual ·": "train.actualLabel",
  "CONFIRMED SETS": "train.confirmed",
  "Confirmed sets are saved. You can leave this screen and resume from TRAIN.":
    "train.confirmedNote",
  ACTUAL: "train.actual",
  "Actual seconds": "train.actualSeconds",
  "Actual reps": "train.actualReps",
  "Actual weight kg": "train.actualKg",
  "SAVING SET…": "train.savingSet",
  "COMPLETE SET": "train.completeSet",
  "Duration · includes rest and time away": "train.durationNote",
  "sets completed": "train.setsCompleted",
  complete: "train.completeSuffix",
  Reps: "units.reps",
  reps: "units.repsShort",
  Seconds: "units.seconds",
  sec: "units.sec",
  sets: "units.sets",
  Minutes: "units.minutes",
  min: "units.min",
  Exercises: "units.exercises",
  exercises: "units.exercisePlural",
  exercise: "units.exercise",
  "EXERCISE NAME": "exercise.name",
  "PRIMARY BODY PART": "exercise.primary",
  "SECONDARY BODY PARTS · OPTIONAL": "exercise.secondary",
  EQUIPMENT: "exercise.equipment",
  "TRACKING TYPE": "exercise.trackingType",
  CATEGORY: "exercise.category",
  "SAVE EXERCISE": "exercise.save",
  "ADD EXERCISE": "exercise.add",
  "SEARCH EXERCISES": "exercise.search",
  "Search by name": "exercise.searchPlaceholder",
  "HIDE FILTERS": "exercise.hideFilters",
  FILTERS: "exercise.filters",
  "BODY PART": "exercise.bodyPart",
  TRACKING: "exercise.tracking",
  "CLEAR FILTERS": "exercise.clearFilters",
  "No exercise found": "exercise.none",
  RECENT: "exercise.recent",
  "ALL EXERCISES": "exercise.all",
  "Your recent selections appear here.": "exercise.recentEmpty",
  "No matching exercises.": "exercise.matchEmpty",
  "TRAINING PROFILE": "coach.profile",
  "YOUR PREFERENCES": "coach.preferences",
  "RETRY PROFILE": "coach.retry",
  "RETRY TRAINING PROFILE": "coach.retryProfile",
  "RESET COACH PROFILE": "coach.reset",
  "RESET COACH PROFILE?": "coach.resetQuestion",
  "Back up and clear your profile only. Workouts and history are unchanged.":
    "coach.resetNote",
  "Reset preferences and baseline entries only. A raw backup is saved first. Workouts and session history remain unchanged.":
    "coach.resetDetail",
  "Loading preferences…": "coach.loading",
  "MAKE IT YOUR TRAINING": "coach.setupTitle",
  "Set up a few preferences and an optional starting reference. Manual workouts are always available.":
    "coach.setupNote",
  "SET UP YOUR PROFILE": "coach.setup",
  "TRY WITH DEFAULTS": "coach.defaults",
  "SKIP FOR NOW": "coach.skip",
  "TODAY'S TRAINING": "coach.today",
  "A short proposal from your preferences and confirmed training.":
    "coach.todayNote",
  "GENERATE WORKOUT": "coach.generate",
  "CUSTOMIZE TODAY": "coach.customizeToday",
  "EDIT TRAINING PROFILE": "coach.editProfile",
  "JUST FOR TODAY": "coach.justToday",
  "These choices do not change your saved profile.": "coach.temporaryNote",
  "ALLOW FAMILIAR CUSTOM EXERCISES": "coach.allowCustom",
  "Difficulty is unknown. Select only movements you know and want to consider.":
    "coach.customNote",
  "GENERATE WITH THESE CHOICES": "coach.generateChoices",
  "USE PROFILE DEFAULTS": "coach.useDefaults",
  "ADJUST YOUR PLAN": "coach.adjust",
  "CREATE MANUAL WORKOUT": "coach.manual",
  "REVIEW YOUR WORKOUT": "coach.review",
  "Nothing is saved until you choose SAVE RECOMMENDATION or save in the workout builder.":
    "coach.saveNote",
  "FROM COMPLETED TRAINING": "coach.fromSession",
  "FROM YOUR BASELINE": "coach.fromBaseline",
  "CHOOSE STARTING LOAD": "coach.chooseLoad",
  "INITIAL SUGGESTION": "coach.initial",
  "Choose load": "coach.load",
  "Choose a comfortable load": "coach.comfortableLoad",
  "Load confirmed ·": "coach.loadConfirmed",
  "SAVE RECOMMENDATION": "coach.save",
  "CUSTOMIZE WORKOUT": "coach.customize",
  "You can change the focus or equipment to get a different proposal. Resting today is also a valid choice.":
    "coach.restNote",
  "TARGET BODY PARTS · EMPTY = AUTOMATIC": "coach.focus",
  "TRAINING LOCATION": "coach.location",
  "AVAILABLE EQUIPMENT": "coach.equipment",
  "Select only what you can use at this location. Bodyweight is always available.":
    "coach.equipmentNote",
  "Available minutes": "coach.minutes",
  "Preferred exercise count": "coach.exerciseCount",
  "Exercise count is a maximum; a shorter plan may fit your time better.":
    "coach.countNote",
  "Weight · kg": "train.weightLabel",
  "· Set": "train.setNumber",
  "exercises ·": "train.exercisesSeparator",
  "· COMPLETE": "train.completedSeparator",
  "sets · Completed": "train.historySeparator",
  "· approximately": "coach.approximately",
  "· Rest": "coach.rest",
  seconds: "units.secondsShort",
  "Targets repeat a conservative result from your latest matching session; no automatic increase.":
    "coach.evidence.session",
  "Target uses your optional baseline, not workout history.":
    "coach.evidence.baseline",
  "No recent working load is known. Choose and confirm a comfortable starting load.":
    "coach.evidence.load",
  "You selected this custom movement. Its difficulty is unknown; review this initial target.":
    "coach.evidence.custom",
  "Initial suggestion without performance evidence. Adjust to a comfortable effort.":
    "coach.evidence.initial",
  "Choose a valid date before generating a workout.": "coach.reason.date",
  "Check your training profile before generating a workout.":
    "coach.reason.profile",
  "Check your time, exercise count and training preferences.":
    "coach.reason.preferences",
  "Workout history is unavailable. Retry session storage or create a manual workout.":
    "coach.reason.history",
  "A selected custom exercise is no longer available. Update your choices.":
    "coach.reason.custom",
  "No compatible starting recommendation is available for this focus, equipment and performance evidence. Change your choices or create a manual workout.":
    "coach.reason.noPlan",
  "The library cannot cover every selected body part within this exercise count and equipment. Adjust the focus/count or create a manual workout.":
    "coach.reason.coverage",
  "These targets and rest do not fit the available time. Allow more time, narrow your focus or make a manual workout.":
    "coach.reason.time",
  "Duration is approximate; rests are retained. Adjust targets to a comfortable effort.":
    "coach.explanation.duration",
  "Using beginner, strength and bodyweight defaults until you save a profile.":
    "coach.explanation.defaults",
  "Recent confirmed training influences exercise selection; this is not a recovery estimate. Rest is also an option.":
    "coach.explanation.recent",
  "Recently involved areas use one set in this proposal.":
    "coach.explanation.oneSet",
  "This exercise is used in a saved workout. Remove it from those workouts before changing its tracking type.":
    "error.exerciseInUseTracking",
  "This exercise is used in a saved workout. Remove it from those workouts before deleting it.":
    "error.exerciseInUseDelete",
  "Please check the name, exercises and targets before saving.":
    "error.invalidWorkout",
  "Saved training data could not be read. Your data has been kept unchanged.":
    "error.trainingRead",
  "Saved training data is incompatible or damaged. Your data has been kept unchanged.":
    "error.trainingInvalid",
  "Training data has not loaded. Please retry.": "error.trainingLoading",
  "Check the actual result before completing this set.": "error.actual",
  "Season data is unavailable or incompatible. Saved history is preserved. Please retry.":
    "error.seasonData",
  "A valid Career and Player are required.": "error.seasonOwner",
  "Season Career identity mismatch. Saved data is preserved.":
    "error.seasonIdentity",
  "Active Season Club does not match Career.": "error.seasonClub",
  "Complete your previous Season first.": "error.seasonPrevious",
  "Device calendar is earlier than saved Season history.": "error.seasonClock",
  "Complete this Season after its calendar month ends.": "error.seasonClose",
  "Workout history could not be validated for Season PRs.": "error.seasonPR",
};
